import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const crops = [
  // Leafy Greens
  {
    name: 'lettuce',
    category: 'vegetable',
    daysToMaturity: 45,
    daysToGermination: 7,
    sunRequirement: 'partial',
    difficulty: 'easy',
    spacingInRow: 6,
    spacingBetweenRows: 12,
    minHardinessZone: 3,
    maxHardinessZone: 9,
    frostTolerant: true,
  },
  {
    name: 'spinach',
    category: 'vegetable',
    daysToMaturity: 40,
    daysToGermination: 7,
    sunRequirement: 'partial',
    difficulty: 'easy',
    spacingInRow: 4,
    spacingBetweenRows: 12,
    minHardinessZone: 2,
    maxHardinessZone: 9,
    frostTolerant: true,
  },
  {
    name: 'kale',
    category: 'vegetable',
    daysToMaturity: 55,
    daysToGermination: 5,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 12,
    spacingBetweenRows: 18,
    minHardinessZone: 2,
    maxHardinessZone: 11,
    frostTolerant: true,
  },
  {
    name: 'arugula',
    category: 'vegetable',
    daysToMaturity: 35,
    daysToGermination: 5,
    sunRequirement: 'partial',
    difficulty: 'easy',
    spacingInRow: 4,
    spacingBetweenRows: 10,
    minHardinessZone: 3,
    maxHardinessZone: 9,
    frostTolerant: true,
  },
  {
    name: 'swiss chard',
    category: 'vegetable',
    daysToMaturity: 50,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 6,
    spacingBetweenRows: 18,
    minHardinessZone: 3,
    maxHardinessZone: 10,
    frostTolerant: true,
  },
  {
    name: 'collard greens',
    category: 'vegetable',
    daysToMaturity: 60,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 18,
    spacingBetweenRows: 24,
    minHardinessZone: 3,
    maxHardinessZone: 11,
    frostTolerant: true,
  },
  {
    name: 'mustard greens',
    category: 'vegetable',
    daysToMaturity: 40,
    daysToGermination: 5,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 6,
    spacingBetweenRows: 12,
    minHardinessZone: 2,
    maxHardinessZone: 10,
    frostTolerant: true,
  },
  
  // Brassicas
  {
    name: 'broccoli',
    category: 'vegetable',
    daysToMaturity: 70,
    daysToGermination: 5,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 18,
    spacingBetweenRows: 24,
    minHardinessZone: 3,
    maxHardinessZone: 10,
    frostTolerant: true,
  },
  {
    name: 'cabbage',
    category: 'vegetable',
    daysToMaturity: 80,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 18,
    spacingBetweenRows: 24,
    minHardinessZone: 1,
    maxHardinessZone: 10,
    frostTolerant: true,
  },
  {
    name: 'cauliflower',
    category: 'vegetable',
    daysToMaturity: 75,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'hard',
    spacingInRow: 18,
    spacingBetweenRows: 24,
    minHardinessZone: 3,
    maxHardinessZone: 10,
    frostTolerant: true,
  },
  {
    name: 'brussels sprouts',
    category: 'vegetable',
    daysToMaturity: 90,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 24,
    spacingBetweenRows: 30,
    minHardinessZone: 3,
    maxHardinessZone: 9,
    frostTolerant: true,
  },
  {
    name: 'kohlrabi',
    category: 'vegetable',
    daysToMaturity: 55,
    daysToGermination: 5,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 6,
    spacingBetweenRows: 12,
    minHardinessZone: 2,
    maxHardinessZone: 10,
    frostTolerant: true,
  },
  
  // Legumes
  {
    name: 'peas',
    category: 'vegetable',
    daysToMaturity: 60,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 2,
    spacingBetweenRows: 18,
    minHardinessZone: 2,
    maxHardinessZone: 11,
    frostTolerant: true,
  },
  {
    name: 'beans',
    category: 'vegetable',
    daysToMaturity: 55,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 3,
    spacingBetweenRows: 18,
    minHardinessZone: 3,
    maxHardinessZone: 10,
    frostTolerant: false,
  },
  {
    name: 'pole beans',
    category: 'vegetable',
    daysToMaturity: 65,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 6,
    spacingBetweenRows: 36,
    minHardinessZone: 3,
    maxHardinessZone: 10,
    frostTolerant: false,
  },
  {
    name: 'snap peas',
    category: 'vegetable',
    daysToMaturity: 65,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 2,
    spacingBetweenRows: 18,
    minHardinessZone: 2,
    maxHardinessZone: 11,
    frostTolerant: true,
  },
  {
    name: 'edamame',
    category: 'vegetable',
    daysToMaturity: 75,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 4,
    spacingBetweenRows: 24,
    minHardinessZone: 5,
    maxHardinessZone: 10,
    frostTolerant: false,
  },
  
  // Nightshades
  {
    name: 'tomatoes',
    category: 'vegetable',
    daysToMaturity: 75,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 24,
    spacingBetweenRows: 36,
    minHardinessZone: 5,
    maxHardinessZone: 11,
    frostTolerant: false,
  },
  {
    name: 'cherry tomatoes',
    category: 'vegetable',
    daysToMaturity: 65,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 24,
    spacingBetweenRows: 36,
    minHardinessZone: 5,
    maxHardinessZone: 11,
    frostTolerant: false,
  },
  {
    name: 'peppers',
    category: 'vegetable',
    daysToMaturity: 70,
    daysToGermination: 10,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 18,
    spacingBetweenRows: 24,
    minHardinessZone: 5,
    maxHardinessZone: 11,
    frostTolerant: false,
  },
  {
    name: 'hot peppers',
    category: 'vegetable',
    daysToMaturity: 75,
    daysToGermination: 10,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 18,
    spacingBetweenRows: 24,
    minHardinessZone: 5,
    maxHardinessZone: 11,
    frostTolerant: false,
  },
  {
    name: 'eggplant',
    category: 'vegetable',
    daysToMaturity: 80,
    daysToGermination: 10,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 24,
    spacingBetweenRows: 30,
    minHardinessZone: 5,
    maxHardinessZone: 11,
    frostTolerant: false,
  },
  {
    name: 'tomatillos',
    category: 'vegetable',
    daysToMaturity: 75,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 24,
    spacingBetweenRows: 36,
    minHardinessZone: 5,
    maxHardinessZone: 11,
    frostTolerant: false,
  },
  
  // Cucurbits
  {
    name: 'cucumbers',
    category: 'vegetable',
    daysToMaturity: 55,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 12,
    spacingBetweenRows: 36,
    minHardinessZone: 4,
    maxHardinessZone: 11,
    frostTolerant: false,
  },
  {
    name: 'squash',
    category: 'vegetable',
    daysToMaturity: 50,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 24,
    spacingBetweenRows: 48,
    minHardinessZone: 3,
    maxHardinessZone: 10,
    frostTolerant: false,
  },
  {
    name: 'zucchini',
    category: 'vegetable',
    daysToMaturity: 45,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 24,
    spacingBetweenRows: 36,
    minHardinessZone: 3,
    maxHardinessZone: 10,
    frostTolerant: false,
  },
  {
    name: 'pumpkins',
    category: 'vegetable',
    daysToMaturity: 100,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 36,
    spacingBetweenRows: 72,
    minHardinessZone: 3,
    maxHardinessZone: 10,
    frostTolerant: false,
  },
  {
    name: 'watermelon',
    category: 'fruit',
    daysToMaturity: 85,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 36,
    spacingBetweenRows: 72,
    minHardinessZone: 5,
    maxHardinessZone: 11,
    frostTolerant: false,
  },
  {
    name: 'cantaloupe',
    category: 'fruit',
    daysToMaturity: 80,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 24,
    spacingBetweenRows: 60,
    minHardinessZone: 5,
    maxHardinessZone: 11,
    frostTolerant: false,
  },
  {
    name: 'honeydew',
    category: 'fruit',
    daysToMaturity: 85,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 24,
    spacingBetweenRows: 60,
    minHardinessZone: 5,
    maxHardinessZone: 11,
    frostTolerant: false,
  },
  
  // Root Vegetables
  {
    name: 'carrots',
    category: 'vegetable',
    daysToMaturity: 70,
    daysToGermination: 14,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 2,
    spacingBetweenRows: 12,
    minHardinessZone: 3,
    maxHardinessZone: 10,
    frostTolerant: true,
  },
  {
    name: 'beets',
    category: 'vegetable',
    daysToMaturity: 55,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 3,
    spacingBetweenRows: 12,
    minHardinessZone: 2,
    maxHardinessZone: 10,
    frostTolerant: true,
  },
  {
    name: 'radishes',
    category: 'vegetable',
    daysToMaturity: 25,
    daysToGermination: 5,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 2,
    spacingBetweenRows: 6,
    minHardinessZone: 2,
    maxHardinessZone: 11,
    frostTolerant: true,
  },
  {
    name: 'turnips',
    category: 'vegetable',
    daysToMaturity: 50,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 4,
    spacingBetweenRows: 12,
    minHardinessZone: 2,
    maxHardinessZone: 10,
    frostTolerant: true,
  },
  {
    name: 'parsnips',
    category: 'vegetable',
    daysToMaturity: 120,
    daysToGermination: 14,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 3,
    spacingBetweenRows: 12,
    minHardinessZone: 2,
    maxHardinessZone: 9,
    frostTolerant: true,
  },
  {
    name: 'rutabaga',
    category: 'vegetable',
    daysToMaturity: 90,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 6,
    spacingBetweenRows: 18,
    minHardinessZone: 3,
    maxHardinessZone: 9,
    frostTolerant: true,
  },
  {
    name: 'potatoes',
    category: 'vegetable',
    daysToMaturity: 90,
    daysToGermination: 14,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 12,
    spacingBetweenRows: 30,
    minHardinessZone: 3,
    maxHardinessZone: 10,
    frostTolerant: false,
  },
  {
    name: 'sweet potatoes',
    category: 'vegetable',
    daysToMaturity: 100,
    daysToGermination: 14,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 12,
    spacingBetweenRows: 36,
    minHardinessZone: 8,
    maxHardinessZone: 11,
    frostTolerant: false,
  },
  
  // Alliums
  {
    name: 'onions',
    category: 'vegetable',
    daysToMaturity: 100,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 4,
    spacingBetweenRows: 12,
    minHardinessZone: 3,
    maxHardinessZone: 10,
    frostTolerant: true,
  },
  {
    name: 'garlic',
    category: 'vegetable',
    daysToMaturity: 240,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 6,
    spacingBetweenRows: 12,
    minHardinessZone: 3,
    maxHardinessZone: 9,
    frostTolerant: true,
  },
  {
    name: 'leeks',
    category: 'vegetable',
    daysToMaturity: 120,
    daysToGermination: 10,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 6,
    spacingBetweenRows: 12,
    minHardinessZone: 3,
    maxHardinessZone: 9,
    frostTolerant: true,
  },
  {
    name: 'scallions',
    category: 'vegetable',
    daysToMaturity: 60,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 2,
    spacingBetweenRows: 6,
    minHardinessZone: 3,
    maxHardinessZone: 10,
    frostTolerant: true,
  },
  {
    name: 'shallots',
    category: 'vegetable',
    daysToMaturity: 90,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 6,
    spacingBetweenRows: 12,
    minHardinessZone: 4,
    maxHardinessZone: 9,
    frostTolerant: true,
  },
  
  // Corn & Grains
  {
    name: 'corn',
    category: 'vegetable',
    daysToMaturity: 75,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 12,
    spacingBetweenRows: 30,
    minHardinessZone: 4,
    maxHardinessZone: 10,
    frostTolerant: false,
  },
  
  // Herbs
  {
    name: 'basil',
    category: 'herb',
    daysToMaturity: 60,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 10,
    spacingBetweenRows: 12,
    minHardinessZone: 9,
    maxHardinessZone: 11,
    frostTolerant: false,
  },
  {
    name: 'cilantro',
    category: 'herb',
    daysToMaturity: 50,
    daysToGermination: 7,
    sunRequirement: 'partial',
    difficulty: 'easy',
    spacingInRow: 6,
    spacingBetweenRows: 8,
    minHardinessZone: 3,
    maxHardinessZone: 11,
    frostTolerant: true,
  },
  {
    name: 'parsley',
    category: 'herb',
    daysToMaturity: 70,
    daysToGermination: 14,
    sunRequirement: 'partial',
    difficulty: 'easy',
    spacingInRow: 8,
    spacingBetweenRows: 12,
    minHardinessZone: 4,
    maxHardinessZone: 9,
    frostTolerant: true,
  },
  {
    name: 'dill',
    category: 'herb',
    daysToMaturity: 70,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 12,
    spacingBetweenRows: 12,
    minHardinessZone: 2,
    maxHardinessZone: 11,
    frostTolerant: true,
  },
  {
    name: 'oregano',
    category: 'herb',
    daysToMaturity: 90,
    daysToGermination: 10,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 12,
    spacingBetweenRows: 18,
    minHardinessZone: 5,
    maxHardinessZone: 10,
    frostTolerant: false,
  },
  {
    name: 'thyme',
    category: 'herb',
    daysToMaturity: 90,
    daysToGermination: 14,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 12,
    spacingBetweenRows: 12,
    minHardinessZone: 5,
    maxHardinessZone: 9,
    frostTolerant: false,
  },
  {
    name: 'rosemary',
    category: 'herb',
    daysToMaturity: 90,
    daysToGermination: 21,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 24,
    spacingBetweenRows: 24,
    minHardinessZone: 8,
    maxHardinessZone: 10,
    frostTolerant: false,
  },
  {
    name: 'sage',
    category: 'herb',
    daysToMaturity: 90,
    daysToGermination: 14,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 18,
    spacingBetweenRows: 24,
    minHardinessZone: 5,
    maxHardinessZone: 9,
    frostTolerant: false,
  },
  {
    name: 'mint',
    category: 'herb',
    daysToMaturity: 90,
    daysToGermination: 10,
    sunRequirement: 'partial',
    difficulty: 'easy',
    spacingInRow: 18,
    spacingBetweenRows: 24,
    minHardinessZone: 3,
    maxHardinessZone: 11,
    frostTolerant: true,
  },
  {
    name: 'chives',
    category: 'herb',
    daysToMaturity: 60,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 6,
    spacingBetweenRows: 8,
    minHardinessZone: 3,
    maxHardinessZone: 9,
    frostTolerant: true,
  },
  
  // Other Vegetables
  {
    name: 'asparagus',
    category: 'vegetable',
    daysToMaturity: 730,
    daysToGermination: 21,
    sunRequirement: 'full',
    difficulty: 'hard',
    spacingInRow: 18,
    spacingBetweenRows: 36,
    minHardinessZone: 3,
    maxHardinessZone: 8,
    frostTolerant: true,
  },
  {
    name: 'celery',
    category: 'vegetable',
    daysToMaturity: 85,
    daysToGermination: 14,
    sunRequirement: 'full',
    difficulty: 'hard',
    spacingInRow: 6,
    spacingBetweenRows: 24,
    minHardinessZone: 5,
    maxHardinessZone: 10,
    frostTolerant: false,
  },
  {
    name: 'okra',
    category: 'vegetable',
    daysToMaturity: 60,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 12,
    spacingBetweenRows: 36,
    minHardinessZone: 7,
    maxHardinessZone: 11,
    frostTolerant: false,
  },
  {
    name: 'artichokes',
    category: 'vegetable',
    daysToMaturity: 180,
    daysToGermination: 14,
    sunRequirement: 'full',
    difficulty: 'hard',
    spacingInRow: 36,
    spacingBetweenRows: 48,
    minHardinessZone: 7,
    maxHardinessZone: 11,
    frostTolerant: false,
  },
  
  // Fruits & Berries
  {
    name: 'strawberries',
    category: 'fruit',
    daysToMaturity: 90,
    daysToGermination: 14,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 12,
    spacingBetweenRows: 36,
    minHardinessZone: 3,
    maxHardinessZone: 10,
    frostTolerant: true,
  },
  {
    name: 'blueberries',
    category: 'fruit',
    daysToMaturity: 365,
    daysToGermination: 30,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 48,
    spacingBetweenRows: 60,
    minHardinessZone: 3,
    maxHardinessZone: 7,
    frostTolerant: true,
  },
  {
    name: 'raspberries',
    category: 'fruit',
    daysToMaturity: 365,
    daysToGermination: 21,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 24,
    spacingBetweenRows: 72,
    minHardinessZone: 4,
    maxHardinessZone: 8,
    frostTolerant: true,
  },
  {
    name: 'blackberries',
    category: 'fruit',
    daysToMaturity: 365,
    daysToGermination: 21,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 36,
    spacingBetweenRows: 72,
    minHardinessZone: 5,
    maxHardinessZone: 9,
    frostTolerant: true,
  },
  
  // Asian Vegetables
  {
    name: 'bok choy',
    category: 'vegetable',
    daysToMaturity: 45,
    daysToGermination: 5,
    sunRequirement: 'partial',
    difficulty: 'easy',
    spacingInRow: 8,
    spacingBetweenRows: 12,
    minHardinessZone: 3,
    maxHardinessZone: 10,
    frostTolerant: true,
  },
  {
    name: 'napa cabbage',
    category: 'vegetable',
    daysToMaturity: 70,
    daysToGermination: 5,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 12,
    spacingBetweenRows: 18,
    minHardinessZone: 3,
    maxHardinessZone: 10,
    frostTolerant: true,
  },
  {
    name: 'daikon radish',
    category: 'vegetable',
    daysToMaturity: 60,
    daysToGermination: 5,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 6,
    spacingBetweenRows: 12,
    minHardinessZone: 2,
    maxHardinessZone: 11,
    frostTolerant: true,
  },
  {
    name: 'mizuna',
    category: 'vegetable',
    daysToMaturity: 40,
    daysToGermination: 5,
    sunRequirement: 'partial',
    difficulty: 'easy',
    spacingInRow: 6,
    spacingBetweenRows: 12,
    minHardinessZone: 3,
    maxHardinessZone: 9,
    frostTolerant: true,
  },
  {
    name: 'tatsoi',
    category: 'vegetable',
    daysToMaturity: 45,
    daysToGermination: 5,
    sunRequirement: 'partial',
    difficulty: 'easy',
    spacingInRow: 6,
    spacingBetweenRows: 12,
    minHardinessZone: 3,
    maxHardinessZone: 9,
    frostTolerant: true,
  },
  {
    name: 'shiso',
    category: 'herb',
    daysToMaturity: 70,
    daysToGermination: 14,
    sunRequirement: 'partial',
    difficulty: 'easy',
    spacingInRow: 12,
    spacingBetweenRows: 18,
    minHardinessZone: 9,
    maxHardinessZone: 11,
    frostTolerant: false,
  },
  
  // Specialty Greens
  {
    name: 'mache',
    category: 'vegetable',
    daysToMaturity: 60,
    daysToGermination: 10,
    sunRequirement: 'partial',
    difficulty: 'easy',
    spacingInRow: 2,
    spacingBetweenRows: 6,
    minHardinessZone: 3,
    maxHardinessZone: 9,
    frostTolerant: true,
  },
  {
    name: 'endive',
    category: 'vegetable',
    daysToMaturity: 75,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 12,
    spacingBetweenRows: 18,
    minHardinessZone: 4,
    maxHardinessZone: 9,
    frostTolerant: true,
  },
  {
    name: 'radicchio',
    category: 'vegetable',
    daysToMaturity: 85,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 8,
    spacingBetweenRows: 12,
    minHardinessZone: 3,
    maxHardinessZone: 9,
    frostTolerant: true,
  },
  {
    name: 'watercress',
    category: 'vegetable',
    daysToMaturity: 50,
    daysToGermination: 7,
    sunRequirement: 'partial',
    difficulty: 'medium',
    spacingInRow: 4,
    spacingBetweenRows: 8,
    minHardinessZone: 3,
    maxHardinessZone: 11,
    frostTolerant: true,
  },
  {
    name: 'sorrel',
    category: 'herb',
    daysToMaturity: 60,
    daysToGermination: 10,
    sunRequirement: 'partial',
    difficulty: 'easy',
    spacingInRow: 12,
    spacingBetweenRows: 18,
    minHardinessZone: 3,
    maxHardinessZone: 9,
    frostTolerant: true,
  },
  
  // More Herbs
  {
    name: 'fennel',
    category: 'herb',
    daysToMaturity: 80,
    daysToGermination: 10,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 12,
    spacingBetweenRows: 18,
    minHardinessZone: 5,
    maxHardinessZone: 10,
    frostTolerant: false,
  },
  {
    name: 'lemongrass',
    category: 'herb',
    daysToMaturity: 120,
    daysToGermination: 14,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 24,
    spacingBetweenRows: 24,
    minHardinessZone: 9,
    maxHardinessZone: 11,
    frostTolerant: false,
  },
  {
    name: 'lavender',
    category: 'herb',
    daysToMaturity: 90,
    daysToGermination: 21,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 18,
    spacingBetweenRows: 24,
    minHardinessZone: 5,
    maxHardinessZone: 9,
    frostTolerant: false,
  },
  {
    name: 'tarragon',
    category: 'herb',
    daysToMaturity: 90,
    daysToGermination: 14,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 18,
    spacingBetweenRows: 24,
    minHardinessZone: 4,
    maxHardinessZone: 8,
    frostTolerant: false,
  },
  {
    name: 'marjoram',
    category: 'herb',
    daysToMaturity: 90,
    daysToGermination: 10,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 8,
    spacingBetweenRows: 12,
    minHardinessZone: 9,
    maxHardinessZone: 11,
    frostTolerant: false,
  },
  {
    name: 'chamomile',
    category: 'herb',
    daysToMaturity: 60,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 6,
    spacingBetweenRows: 8,
    minHardinessZone: 3,
    maxHardinessZone: 9,
    frostTolerant: false,
  },
  {
    name: 'lemon balm',
    category: 'herb',
    daysToMaturity: 70,
    daysToGermination: 14,
    sunRequirement: 'partial',
    difficulty: 'easy',
    spacingInRow: 18,
    spacingBetweenRows: 24,
    minHardinessZone: 4,
    maxHardinessZone: 9,
    frostTolerant: false,
  },
  
  // Specialty Vegetables
  {
    name: 'fennel bulb',
    category: 'vegetable',
    daysToMaturity: 80,
    daysToGermination: 10,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 12,
    spacingBetweenRows: 18,
    minHardinessZone: 5,
    maxHardinessZone: 10,
    frostTolerant: false,
  },
  {
    name: 'rhubarb',
    category: 'vegetable',
    daysToMaturity: 365,
    daysToGermination: 21,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 36,
    spacingBetweenRows: 48,
    minHardinessZone: 3,
    maxHardinessZone: 8,
    frostTolerant: true,
  },
  {
    name: 'horseradish',
    category: 'vegetable',
    daysToMaturity: 150,
    daysToGermination: 14,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 18,
    spacingBetweenRows: 30,
    minHardinessZone: 3,
    maxHardinessZone: 9,
    frostTolerant: true,
  },
  {
    name: 'ginger',
    category: 'vegetable',
    daysToMaturity: 240,
    daysToGermination: 14,
    sunRequirement: 'partial',
    difficulty: 'hard',
    spacingInRow: 8,
    spacingBetweenRows: 12,
    minHardinessZone: 9,
    maxHardinessZone: 11,
    frostTolerant: false,
  },
  {
    name: 'turmeric',
    category: 'vegetable',
    daysToMaturity: 240,
    daysToGermination: 14,
    sunRequirement: 'partial',
    difficulty: 'hard',
    spacingInRow: 8,
    spacingBetweenRows: 12,
    minHardinessZone: 9,
    maxHardinessZone: 11,
    frostTolerant: false,
  },
  
  // Winter Squash Varieties
  {
    name: 'butternut squash',
    category: 'vegetable',
    daysToMaturity: 85,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 24,
    spacingBetweenRows: 60,
    minHardinessZone: 3,
    maxHardinessZone: 10,
    frostTolerant: false,
  },
  {
    name: 'acorn squash',
    category: 'vegetable',
    daysToMaturity: 80,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 24,
    spacingBetweenRows: 60,
    minHardinessZone: 3,
    maxHardinessZone: 10,
    frostTolerant: false,
  },
  {
    name: 'spaghetti squash',
    category: 'vegetable',
    daysToMaturity: 90,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 24,
    spacingBetweenRows: 60,
    minHardinessZone: 3,
    maxHardinessZone: 10,
    frostTolerant: false,
  },
  {
    name: 'delicata squash',
    category: 'vegetable',
    daysToMaturity: 80,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 24,
    spacingBetweenRows: 48,
    minHardinessZone: 3,
    maxHardinessZone: 10,
    frostTolerant: false,
  },
  
  // More Tomato Varieties
  {
    name: 'roma tomatoes',
    category: 'vegetable',
    daysToMaturity: 80,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 24,
    spacingBetweenRows: 36,
    minHardinessZone: 5,
    maxHardinessZone: 11,
    frostTolerant: false,
  },
  {
    name: 'heirloom tomatoes',
    category: 'vegetable',
    daysToMaturity: 85,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 24,
    spacingBetweenRows: 36,
    minHardinessZone: 5,
    maxHardinessZone: 11,
    frostTolerant: false,
  },
  
  // More Bean Varieties
  {
    name: 'lima beans',
    category: 'vegetable',
    daysToMaturity: 70,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 6,
    spacingBetweenRows: 24,
    minHardinessZone: 4,
    maxHardinessZone: 10,
    frostTolerant: false,
  },
  {
    name: 'fava beans',
    category: 'vegetable',
    daysToMaturity: 85,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 6,
    spacingBetweenRows: 18,
    minHardinessZone: 3,
    maxHardinessZone: 9,
    frostTolerant: true,
  },
  
  // Pea Varieties
  {
    name: 'snow peas',
    category: 'vegetable',
    daysToMaturity: 65,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 2,
    spacingBetweenRows: 18,
    minHardinessZone: 2,
    maxHardinessZone: 11,
    frostTolerant: true,
  },
  
  // Flowers (edible)
  {
    name: 'nasturtiums',
    category: 'flower',
    daysToMaturity: 50,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 12,
    spacingBetweenRows: 12,
    minHardinessZone: 2,
    maxHardinessZone: 11,
    frostTolerant: false,
  },
  {
    name: 'marigolds',
    category: 'flower',
    daysToMaturity: 50,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 10,
    spacingBetweenRows: 12,
    minHardinessZone: 2,
    maxHardinessZone: 11,
    frostTolerant: false,
  },
  {
    name: 'sunflowers',
    category: 'flower',
    daysToMaturity: 70,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 12,
    spacingBetweenRows: 24,
    minHardinessZone: 2,
    maxHardinessZone: 11,
    frostTolerant: false,
  },
  {
    name: 'calendula',
    category: 'flower',
    daysToMaturity: 55,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 12,
    spacingBetweenRows: 12,
    minHardinessZone: 2,
    maxHardinessZone: 11,
    frostTolerant: true,
  },
  {
    name: 'pansies',
    category: 'flower',
    daysToMaturity: 70,
    daysToGermination: 10,
    sunRequirement: 'partial',
    difficulty: 'easy',
    spacingInRow: 8,
    spacingBetweenRows: 8,
    minHardinessZone: 6,
    maxHardinessZone: 10,
    frostTolerant: true,
  },
  {
    name: 'violas',
    category: 'flower',
    daysToMaturity: 60,
    daysToGermination: 10,
    sunRequirement: 'partial',
    difficulty: 'easy',
    spacingInRow: 6,
    spacingBetweenRows: 8,
    minHardinessZone: 6,
    maxHardinessZone: 10,
    frostTolerant: true,
  },
  
  // Cover Crops
  {
    name: 'clover',
    category: 'vegetable',
    daysToMaturity: 60,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 2,
    spacingBetweenRows: 6,
    minHardinessZone: 3,
    maxHardinessZone: 10,
    frostTolerant: true,
  },
  {
    name: 'winter rye',
    category: 'vegetable',
    daysToMaturity: 180,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 2,
    spacingBetweenRows: 6,
    minHardinessZone: 3,
    maxHardinessZone: 8,
    frostTolerant: true,
  },
  // Asian Vegetables
  {
    name: 'yu choy',
    category: 'vegetable',
    daysToMaturity: 45,
    daysToGermination: 5,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 6,
    spacingBetweenRows: 12,
    minHardinessZone: 4,
    maxHardinessZone: 9,
    frostTolerant: true,
  },
  {
    name: 'gai lan',
    category: 'vegetable',
    daysToMaturity: 50,
    daysToGermination: 5,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 8,
    spacingBetweenRows: 12,
    minHardinessZone: 4,
    maxHardinessZone: 9,
    frostTolerant: true,
  },
  {
    name: 'bitter melon',
    category: 'vegetable',
    daysToMaturity: 80,
    daysToGermination: 10,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 24,
    spacingBetweenRows: 36,
    minHardinessZone: 8,
    maxHardinessZone: 11,
    frostTolerant: false,
  },
  {
    name: 'yard long beans',
    category: 'vegetable',
    daysToMaturity: 75,
    daysToGermination: 10,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 6,
    spacingBetweenRows: 24,
    minHardinessZone: 5,
    maxHardinessZone: 11,
    frostTolerant: false,
  },
  {
    name: 'mung beans',
    category: 'vegetable',
    daysToMaturity: 90,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 4,
    spacingBetweenRows: 18,
    minHardinessZone: 3,
    maxHardinessZone: 10,
    frostTolerant: false,
  },
  // Specialty Lettuce & Greens
  {
    name: 'butterhead lettuce',
    category: 'vegetable',
    daysToMaturity: 55,
    daysToGermination: 7,
    sunRequirement: 'partial',
    difficulty: 'easy',
    spacingInRow: 8,
    spacingBetweenRows: 12,
    minHardinessZone: 3,
    maxHardinessZone: 9,
    frostTolerant: true,
  },
  {
    name: 'romaine lettuce',
    category: 'vegetable',
    daysToMaturity: 65,
    daysToGermination: 7,
    sunRequirement: 'partial',
    difficulty: 'easy',
    spacingInRow: 8,
    spacingBetweenRows: 12,
    minHardinessZone: 3,
    maxHardinessZone: 9,
    frostTolerant: true,
  },
  {
    name: 'oakleaf lettuce',
    category: 'vegetable',
    daysToMaturity: 50,
    daysToGermination: 7,
    sunRequirement: 'partial',
    difficulty: 'easy',
    spacingInRow: 6,
    spacingBetweenRows: 12,
    minHardinessZone: 3,
    maxHardinessZone: 9,
    frostTolerant: true,
  },
  {
    name: 'mesclun mix',
    category: 'vegetable',
    daysToMaturity: 30,
    daysToGermination: 7,
    sunRequirement: 'partial',
    difficulty: 'easy',
    spacingInRow: 2,
    spacingBetweenRows: 8,
    minHardinessZone: 3,
    maxHardinessZone: 9,
    frostTolerant: true,
  },
  // Specialty Peppers
  {
    name: 'shishito peppers',
    category: 'vegetable',
    daysToMaturity: 60,
    daysToGermination: 10,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 18,
    spacingBetweenRows: 24,
    minHardinessZone: 5,
    maxHardinessZone: 11,
    frostTolerant: false,
  },
  {
    name: 'poblano peppers',
    category: 'vegetable',
    daysToMaturity: 65,
    daysToGermination: 10,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 18,
    spacingBetweenRows: 24,
    minHardinessZone: 5,
    maxHardinessZone: 11,
    frostTolerant: false,
  },
  {
    name: 'habanero peppers',
    category: 'vegetable',
    daysToMaturity: 90,
    daysToGermination: 14,
    sunRequirement: 'full',
    difficulty: 'hard',
    spacingInRow: 18,
    spacingBetweenRows: 24,
    minHardinessZone: 9,
    maxHardinessZone: 11,
    frostTolerant: false,
  },
  {
    name: 'banana peppers',
    category: 'vegetable',
    daysToMaturity: 65,
    daysToGermination: 10,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 18,
    spacingBetweenRows: 24,
    minHardinessZone: 5,
    maxHardinessZone: 11,
    frostTolerant: false,
  },
  // Root Vegetables
  {
    name: 'celeriac',
    category: 'vegetable',
    daysToMaturity: 110,
    daysToGermination: 14,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 6,
    spacingBetweenRows: 12,
    minHardinessZone: 3,
    maxHardinessZone: 9,
    frostTolerant: true,
  },
  {
    name: 'salsify',
    category: 'vegetable',
    daysToMaturity: 120,
    daysToGermination: 14,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 4,
    spacingBetweenRows: 12,
    minHardinessZone: 4,
    maxHardinessZone: 8,
    frostTolerant: true,
  },
  {
    name: 'jicama',
    category: 'vegetable',
    daysToMaturity: 150,
    daysToGermination: 14,
    sunRequirement: 'full',
    difficulty: 'hard',
    spacingInRow: 12,
    spacingBetweenRows: 36,
    minHardinessZone: 9,
    maxHardinessZone: 11,
    frostTolerant: false,
  },
  // Specialty Squash
  {
    name: 'kabocha squash',
    category: 'vegetable',
    daysToMaturity: 100,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 36,
    spacingBetweenRows: 48,
    minHardinessZone: 4,
    maxHardinessZone: 11,
    frostTolerant: false,
  },
  {
    name: 'pattypan squash',
    category: 'vegetable',
    daysToMaturity: 50,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 24,
    spacingBetweenRows: 36,
    minHardinessZone: 4,
    maxHardinessZone: 11,
    frostTolerant: false,
  },
  {
    name: 'hubbard squash',
    category: 'vegetable',
    daysToMaturity: 110,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 48,
    spacingBetweenRows: 60,
    minHardinessZone: 4,
    maxHardinessZone: 11,
    frostTolerant: false,
  },
  // Culinary Herbs
  {
    name: 'bay laurel',
    category: 'herb',
    daysToMaturity: 365,
    daysToGermination: 30,
    sunRequirement: 'full',
    difficulty: 'hard',
    spacingInRow: 36,
    spacingBetweenRows: 48,
    minHardinessZone: 8,
    maxHardinessZone: 11,
    frostTolerant: false,
  },
  {
    name: 'curry leaf',
    category: 'herb',
    daysToMaturity: 365,
    daysToGermination: 21,
    sunRequirement: 'full',
    difficulty: 'hard',
    spacingInRow: 24,
    spacingBetweenRows: 36,
    minHardinessZone: 9,
    maxHardinessZone: 11,
    frostTolerant: false,
  },
  {
    name: 'lemon verbena',
    category: 'herb',
    daysToMaturity: 90,
    daysToGermination: 21,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 18,
    spacingBetweenRows: 24,
    minHardinessZone: 8,
    maxHardinessZone: 11,
    frostTolerant: false,
  },
  {
    name: 'stevia',
    category: 'herb',
    daysToMaturity: 120,
    daysToGermination: 14,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 12,
    spacingBetweenRows: 18,
    minHardinessZone: 9,
    maxHardinessZone: 11,
    frostTolerant: false,
  },
  {
    name: 'epazote',
    category: 'herb',
    daysToMaturity: 60,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 12,
    spacingBetweenRows: 18,
    minHardinessZone: 8,
    maxHardinessZone: 11,
    frostTolerant: false,
  },
  {
    name: 'lovage',
    category: 'herb',
    daysToMaturity: 85,
    daysToGermination: 14,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 24,
    spacingBetweenRows: 36,
    minHardinessZone: 3,
    maxHardinessZone: 9,
    frostTolerant: true,
  },
  {
    name: 'anise hyssop',
    category: 'herb',
    daysToMaturity: 70,
    daysToGermination: 10,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 12,
    spacingBetweenRows: 18,
    minHardinessZone: 4,
    maxHardinessZone: 9,
    frostTolerant: true,
  },
  // Edible Flowers
  {
    name: 'borage',
    category: 'flower',
    daysToMaturity: 55,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 12,
    spacingBetweenRows: 18,
    minHardinessZone: 2,
    maxHardinessZone: 11,
    frostTolerant: true,
  },
  {
    name: 'bachelor buttons',
    category: 'flower',
    daysToMaturity: 60,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 6,
    spacingBetweenRows: 12,
    minHardinessZone: 2,
    maxHardinessZone: 11,
    frostTolerant: true,
  },
  {
    name: 'zinnias',
    category: 'flower',
    daysToMaturity: 60,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 12,
    spacingBetweenRows: 18,
    minHardinessZone: 3,
    maxHardinessZone: 10,
    frostTolerant: false,
  },
  {
    name: 'cosmos',
    category: 'flower',
    daysToMaturity: 70,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 12,
    spacingBetweenRows: 18,
    minHardinessZone: 2,
    maxHardinessZone: 11,
    frostTolerant: false,
  },
  {
    name: 'snapdragons',
    category: 'flower',
    daysToMaturity: 80,
    daysToGermination: 10,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 6,
    spacingBetweenRows: 12,
    minHardinessZone: 7,
    maxHardinessZone: 10,
    frostTolerant: true,
  },
  // Microgreens & Sprouts
  {
    name: 'pea shoots',
    category: 'vegetable',
    daysToMaturity: 14,
    daysToGermination: 3,
    sunRequirement: 'partial',
    difficulty: 'easy',
    spacingInRow: 1,
    spacingBetweenRows: 4,
    minHardinessZone: 3,
    maxHardinessZone: 10,
    frostTolerant: true,
  },
  {
    name: 'sunflower sprouts',
    category: 'vegetable',
    daysToMaturity: 10,
    daysToGermination: 2,
    sunRequirement: 'partial',
    difficulty: 'easy',
    spacingInRow: 2,
    spacingBetweenRows: 4,
    minHardinessZone: 3,
    maxHardinessZone: 10,
    frostTolerant: false,
  },
  {
    name: 'radish microgreens',
    category: 'vegetable',
    daysToMaturity: 7,
    daysToGermination: 2,
    sunRequirement: 'partial',
    difficulty: 'easy',
    spacingInRow: 1,
    spacingBetweenRows: 2,
    minHardinessZone: 3,
    maxHardinessZone: 10,
    frostTolerant: true,
  },
  {
    name: 'broccoli microgreens',
    category: 'vegetable',
    daysToMaturity: 10,
    daysToGermination: 3,
    sunRequirement: 'partial',
    difficulty: 'easy',
    spacingInRow: 1,
    spacingBetweenRows: 2,
    minHardinessZone: 3,
    maxHardinessZone: 10,
    frostTolerant: true,
  },
  // Specialty Greens
  {
    name: 'purslane',
    category: 'vegetable',
    daysToMaturity: 40,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 6,
    spacingBetweenRows: 12,
    minHardinessZone: 5,
    maxHardinessZone: 10,
    frostTolerant: false,
  },
  {
    name: 'dandelion greens',
    category: 'vegetable',
    daysToMaturity: 85,
    daysToGermination: 10,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 6,
    spacingBetweenRows: 12,
    minHardinessZone: 3,
    maxHardinessZone: 10,
    frostTolerant: true,
  },
  {
    name: 'amaranth greens',
    category: 'vegetable',
    daysToMaturity: 40,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 12,
    spacingBetweenRows: 18,
    minHardinessZone: 4,
    maxHardinessZone: 11,
    frostTolerant: false,
  },
  {
    name: 'orach',
    category: 'vegetable',
    daysToMaturity: 40,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 8,
    spacingBetweenRows: 12,
    minHardinessZone: 3,
    maxHardinessZone: 9,
    frostTolerant: true,
  },
  // Grains & Seeds
  {
    name: 'quinoa',
    category: 'vegetable',
    daysToMaturity: 120,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 12,
    spacingBetweenRows: 18,
    minHardinessZone: 4,
    maxHardinessZone: 10,
    frostTolerant: true,
  },
  {
    name: 'amaranth grain',
    category: 'vegetable',
    daysToMaturity: 120,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 12,
    spacingBetweenRows: 24,
    minHardinessZone: 4,
    maxHardinessZone: 11,
    frostTolerant: false,
  },
  {
    name: 'buckwheat',
    category: 'vegetable',
    daysToMaturity: 70,
    daysToGermination: 5,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 4,
    spacingBetweenRows: 8,
    minHardinessZone: 3,
    maxHardinessZone: 10,
    frostTolerant: false,
  },
  {
    name: 'flax',
    category: 'vegetable',
    daysToMaturity: 100,
    daysToGermination: 10,
    sunRequirement: 'full',
    difficulty: 'easy',
    spacingInRow: 2,
    spacingBetweenRows: 12,
    minHardinessZone: 3,
    maxHardinessZone: 10,
    frostTolerant: true,
  },
  // Melons
  {
    name: 'crenshaw melon',
    category: 'fruit',
    daysToMaturity: 110,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 48,
    spacingBetweenRows: 72,
    minHardinessZone: 4,
    maxHardinessZone: 11,
    frostTolerant: false,
  },
  {
    name: 'sugar baby watermelon',
    category: 'fruit',
    daysToMaturity: 75,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 36,
    spacingBetweenRows: 60,
    minHardinessZone: 4,
    maxHardinessZone: 11,
    frostTolerant: false,
  },
  {
    name: 'galia melon',
    category: 'fruit',
    daysToMaturity: 85,
    daysToGermination: 7,
    sunRequirement: 'full',
    difficulty: 'medium',
    spacingInRow: 36,
    spacingBetweenRows: 60,
    minHardinessZone: 4,
    maxHardinessZone: 11,
    frostTolerant: false,
  },
];

async function seed() {
  console.log('🌱 Starting crop seed...');

  for (const crop of crops) {
    const existing = await prisma.crop.findFirst({
      where: { name: crop.name },
    });

    if (existing) {
      console.log(`  ✓ ${crop.name} already exists, skipping`);
    } else {
      await prisma.crop.create({ data: crop });
      console.log(`  + Created ${crop.name}`);
    }
  }

  const count = await prisma.crop.count();
  console.log(`\n✅ Seed complete! Total crops in database: ${count}`);
}

seed()
  .catch((error) => {
    console.error('❌ Seed failed:', error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
